### PR TITLE
Drop support for Django 1.8

### PR DESCRIPTION
**Pull request by michael-k**
According to Supported Versions in https://www.djangoproject.com/download/, support for Django 1.8 ended on 2018-04-01.

The django maintainers suggested to drop support for Django < 1.11 in third party libraries with the release of Django 2.0 at December 2, 2017. See https://docs.djangoproject.com/en/2.0/releases/2.0/#third-party-library-support-for-older-version-of-django

The next EOL of a django version will be in 1 year.

### CODE REVIEW

**Comment by urda** [comment]
I'll need to review this, but I will say that losing code coverage will usually result in a rejected PR. Might want to check the codecov report if I don't get to it later this weekend.

**Comment by urda** [comment]
Fixes #68

**Comment by urda** [comment]
I've spun out an issue for seeing why Codecov didn't fail this PR: #71

**Review by urda — CHANGES_REQUESTED** [review]
Code coverage needs to be at 100%, check your tox + html report locally to figure out why.

**Comment by michael-k** [comment]
> check your tox + html report locally to figure out why.

I can see the report on codecov.io.

It was just an now obsolete try-except ImportError.  Fixed

**Comment by urda** [comment]
I'm starting a review now.

**Review by urda — APPROVED** [review]
LGTM, few notes though:

- `CHANGELOG` needed to be updated, but I actually like handling that myself.
- The dates in some of these files needed to be updated for copyright, fixed.
- I think a version bump might be needed for the 1.11.* version, but that is out of scope of this PR.

**Pull request merged**
